// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgJiibPh_EPOrQOIyryc5mYs5bxLHxA1E',
    appId: '1:369665744856:web:a93c227bcee56add831cad',
    messagingSenderId: '369665744856',
    projectId: 'myapp-28179',
    authDomain: 'myapp-28179.firebaseapp.com',
    databaseURL: 'https://myapp-28179-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-28179.appspot.com',
    measurementId: 'G-2RJG4R6HJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFnk6s1w-XwU1P6EOguF-17bUlJbB3NuE',
    appId: '1:369665744856:android:09af927f5d33419d831cad',
    messagingSenderId: '369665744856',
    projectId: 'myapp-28179',
    databaseURL: 'https://myapp-28179-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-28179.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNMq2bQ85pkZhy86jVMEy8j1rZBBPicAc',
    appId: '1:369665744856:ios:01e54120264340ec831cad',
    messagingSenderId: '369665744856',
    projectId: 'myapp-28179',
    databaseURL: 'https://myapp-28179-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-28179.appspot.com',
    iosClientId: '369665744856-mlq8cspd13lntfqkk6h4hefdfgfdmk5m.apps.googleusercontent.com',
    iosBundleId: 'com.myapp.tennis2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNMq2bQ85pkZhy86jVMEy8j1rZBBPicAc',
    appId: '1:369665744856:ios:b22408ed774f6d44831cad',
    messagingSenderId: '369665744856',
    projectId: 'myapp-28179',
    databaseURL: 'https://myapp-28179-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-28179.appspot.com',
    iosClientId: '369665744856-qlkltdngpr1cvgb5eicq8mbvqmi1tl9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tennis2',
  );
}
